### ISSUE TITLE
[bugfix] App crash on api error

### ISSUE THREAD

**Issue by hadi-norouzi** [Kaaveh/ComposeNews#190]
LOG-NET: {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
LOG-NET: <-- END HTTP (187-byte body)
FATAL EXCEPTION: main
Process: ir.composenews, PID: 533
retrofit2.HttpException: HTTP 429 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1ad0b14, Dispatchers.Main.immediate]

**Comment by Kaaveh** [comment]
Yes @hadi-norouzi , this is one of our open issues #185
